[
  { "id": "P-001", "name": "Noble Blush", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-002", "name": "Oud For Glory", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-003", "name": "Ra'ed", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-004", "name": "Saheb", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-005", "name": "Eclaire", "brand": "Lattafa", "price": 29000, "category": "Middle Eastern" },
  { "id": "P-006", "name": "Victoria", "brand": "Lattafa", "price": 29000, "category": "Middle Eastern" },
  { "id": "P-007", "name": "Asad Zanzibar", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-008", "name": "Asad Bourbon", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-009", "name": "Asad Elixir", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-010", "name": "Asad", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-011", "name": "Jazzab Gold", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-012", "name": "Angham", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-013", "name": "Athena", "brand": "Maison Alhambra", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-014", "name": "Qaed Al Fursan Untamed", "brand": "Lattafa", "price": 18000, "category": "Middle Eastern" },
  { "id": "P-015", "name": "Qaed Al Fursan Unlimited", "brand": "Lattafa", "price": 18000, "category": "Middle Eastern" },
  { "id": "P-016", "name": "Fakhar Elixir", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-017", "name": "Stella And Luna", "brand": "Fragrance World", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-018", "name": "Ameer Al Arab", "brand": "Asdaaf", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-019", "name": "Andaleeb", "brand": "Asdaaf", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-020", "name": "Ana Abiyedh Coral", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-021", "name": "Heibah", "brand": "Ard Al Zaafaran", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-022", "name": "Yara Pink", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-023", "name": "Yara Tous", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-024", "name": "Yara Candy", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-025", "name": "Yara Moi", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-026", "name": "Vanilla Voyage", "brand": "Paris Corner", "price": 38000, "category": "Middle Eastern" },
  { "id": "P-027", "name": "Hayaati Black", "brand": "Lattafa", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-028", "name": "Khamrah Dukhan", "brand": "Lattafa", "price": 29500, "category": "Middle Eastern" },
  { "id": "P-029", "name": "The Kingdom Man", "brand": "Lattafa Pride", "price": 29500, "category": "Middle Eastern" },
  { "id": "P-030", "name": "Emeer", "brand": "Lattafa", "price": 29000, "category": "Middle Eastern" },
  { "id": "P-031", "name": "Nebras", "brand": "Lattafa Pride", "price": 25000, "category": "Middle Eastern" },
  { "id": "P-032", "name": "Al Dirgham", "brand": "Ard Al Zaafaran", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-033", "name": "Dalal", "brand": "Al Rehab", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-034", "name": "Bint Hooran", "brand": "Ard Al Zaafaran", "price": 13000, "category": "Middle Eastern" },
  { "id": "P-035", "name": "Club De Nuit Sillage", "brand": "Armaf", "price": 40000, "category": "Middle Eastern" },
  { "id": "P-036", "name": "Club De Nuit Iconic", "brand": "Armaf", "price": 40000, "category": "Middle Eastern" },
  { "id": "P-037", "name": "Satwa", "brand": "Ard Al Zaafaran", "price": 35000, "category": "Middle Eastern" },
  { "id": "P-038", "name": "Nyla", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-039", "name": "Tharwah Gold", "brand": "Lattafa Pride", "price": 29500, "category": "Middle Eastern" },
  { "id": "P-040", "name": "Onyx", "brand": "Lattafa Pride", "price": 20000, "category": "Middle Eastern" },
  { "id": "P-041", "name": "Ishq Al Shuyukh Gold", "brand": "Lattafa Pride", "price": 29000, "category": "Middle Eastern" },
  { "id": "P-042", "name": "Supremacy Collectors Edition", "brand": "Afnan", "price": 60000, "category": "Middle Eastern" },
  { "id": "P-043", "name": "Ansaam Gold", "brand": "Lattafa Pride", "price": 29500, "category": "Middle Eastern" },
  { "id": "P-044", "name": "9PM Rebel", "brand": "Afnan", "price": 39000, "category": "Middle Eastern" },
  { "id": "P-045", "name": "Ajwad", "brand": "Lattafa", "price": 23000, "category": "Middle Eastern" },
  { "id": "P-046", "name": "Fakhar Al Oud", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-047", "name": "Ahlam Al Khaleej", "brand": "Ard Al Zaafaran", "price": 20000, "category": "Middle Eastern" },
  { "id": "P-048", "name": "Gaith", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-049", "name": "Habik", "brand": "Lattafa", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-050", "name": "Rayhaan Corium", "brand": "Rayhaan", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-051", "name": "Taskeen Marina", "brand": "Paris Corner", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-052", "name": "Suspenso", "brand": "Fragrance World", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-053", "name": "Qimmah", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-054", "name": "Art Of Universe", "brand": "Fragrance World", "price": 39000, "category": "Middle Eastern" },
  { "id": "P-055", "name": "Vintage Radio", "brand": "Lattafa Pride", "price": 34000, "category": "Middle Eastern" },
  { "id": "P-056", "name": "Pisa", "brand": "Fragrance World", "price": 48000, "category": "Middle Eastern" },
  { "id": "P-057", "name": "Maharjan Gold", "brand": "Lattafa Pride", "price": 39000, "category": "Middle Eastern" },
  { "id": "P-058", "name": "Eternal Vanille", "brand": "Fragrance World", "price": 39000, "category": "Middle Eastern" },
  { "id": "P-059", "name": "Lattafa Pride 5 In 1 Set", "brand": "Lattafa Pride", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-060", "name": "Afeef", "brand": "Lattafa", "price": 29000, "category": "Middle Eastern" },
  { "id": "P-061", "name": "Tharwah Gold Gift Set", "brand": "Lattafa Pride", "price": 35000, "category": "Middle Eastern" },
  { "id": "P-062", "name": "Nebras Gift Set", "brand": "Lattafa Pride", "price": 34000, "category": "Middle Eastern" },
  { "id": "P-063", "name": "Kaly", "brand": "Unknown", "price": 9000, "category": "Middle Eastern" },
  { "id": "P-064", "name": "Cacao", "brand": "Fragrance World", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-065", "name": "Opulent Musk", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-066", "name": "Opulent Oud", "brand": "Lattafa", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-067", "name": "Monsieur", "brand": "Fragrance World", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-068", "name": "Amethyst", "brand": "Lattafa (Bade'e Al Oud)", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-069", "name": "Ramz Lattafa", "brand": "Lattafa", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-070", "name": "Hayaati Florence", "brand": "Lattafa", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-071", "name": "Hayaati Gold Elixir", "brand": "Lattafa", "price": 14000, "category": "Middle Eastern" },
  { "id": "P-072", "name": "Rave Now", "brand": "Lattafa (Rave)", "price": 19000, "category": "Middle Eastern" },
  { "id": "P-073", "name": "Sublime", "brand": "Lattafa Pride", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-074", "name": "Honor & Glory", "brand": "Lattafa (Bade'e Al Oud)", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-075", "name": "Angham Dupe", "brand": "Unknown", "price": 24000, "category": "Middle Eastern" },
  { "id": "P-Z01", "name": "Golden Decade", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z02", "name": "Amber Fusion", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z03", "name": "Cherry Smoothie 30ml", "brand": "Zara", "price": 15000, "category": "Zara Collection" },
  { "id": "P-Z04", "name": "Deep Garden", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z05", "name": "For Him Red Edition", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z06", "name": "Green Savage And Blue Spirit Set", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z07", "name": "Hypnotic Vanilla", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z08", "name": "Immortal Vanilla", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z09", "name": "Luminous Grove", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z10", "name": "Navy Black And 800 Black Set", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z11", "name": "Nude Bouquet Intense", "brand": "Zara", "price": 28000, "category": "Zara Collection" },
  { "id": "P-Z12", "name": "Seoul And Lisboa Set", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z13", "name": "Sublime Epoque", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z14", "name": "Unusual Fruit", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z15", "name": "Unusual Gourmand", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z16", "name": "Vibrant Leather", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z17", "name": "Vibrant Leather Saline", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z18", "name": "Vibrant Leather Set", "brand": "Zara", "price": 50000, "category": "Zara Collection" },
  { "id": "P-Z19", "name": "Wend - 8PM Till 3 AM", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z20", "name": "Zara Cacao Collection", "brand": "Zara", "price": 40000, "category": "Zara Collection" },
  { "id": "P-Z21", "name": "Zara Night Pour Homme", "brand": "Zara", "price": 40000, "category": "Zara Collection" },
  { "id": "P-Z22", "name": "Zara Tobacco", "brand": "Zara", "price": 40000, "category": "Zara Collection" },
  { "id": "P-Z23", "name": "Zara Vanilla Collection", "brand": "Zara", "price": 40000, "category": "Zara Collection" },
  { "id": "P-Z24", "name": "Captivatingly Paris", "brand": "Zara", "price": 40000, "category": "Zara Collection" },
  { "id": "P-Z25", "name": "For Him Black-Red Edition", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z26", "name": "Platinum Sky", "brand": "Zara", "price": 25000, "category": "Zara Collection" },
  { "id": "P-Z27", "name": "Red Vanilla - Black Amber Set", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z28", "name": "Sand Desert At Sunset", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z29", "name": "Vibrant Leather - Oud", "brand": "Zara", "price": 30000, "category": "Zara Collection" },
  { "id": "P-Z30", "name": "Zara Wood Collection", "brand": "Zara", "price": 40000, "category": "Zara Collection" }
]